(function(){
	function ready(fn){ document.readyState !== 'loading' ? fn() : document.addEventListener('DOMContentLoaded', fn); }

	ready(function(){
		const btn = document.getElementById('purchaseBtn');
		if (!btn) return;
		btn.addEventListener('click', async function(){
			const name = prompt('Enter your full name for the certificate:');
			if (!name) return;
			const course = 'All‑access Membership';

			const key = btn.getAttribute('data-key');
			if (key && window.Razorpay) {
				// Live Razorpay integration (requires backend order creation ideally)
				const options = {
					key,
					amount: 1900,
					currency: 'INR',
					name: 'Teachuonline',
					description: course,
					image: '',
					// order_id: 'order_xxx', // Should be generated by backend for signature verification
					handler: function () {
						generateCertificate(name, course);
						alert('Payment successful! Certificate generated.');
					},
					theme: { color: '#6ea8fe' },
					prefill: { name }
				};
				const rzp = new window.Razorpay(options);
				rzp.open();
				return;
			}

			// Fallback demo: simulate purchase success
			setTimeout(function(){
				generateCertificate(name, course);
				alert('Demo purchase successful! Certificate generated.');
			}, 500);
		});
	});

	function generateCertificate(name, course){
		if (!window.jspdf || !window.jspdf.jsPDF) return;
		const { jsPDF } = window.jspdf;
		const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' });
		const width = doc.internal.pageSize.getWidth();
		const height = doc.internal.pageSize.getHeight();

		doc.setFillColor(18,22,27); doc.rect(0,0,width,height,'F');
		doc.setDrawColor(110,168,254); doc.setLineWidth(4); doc.rect(24,24,width-48,height-48,'S');
		doc.setTextColor(230,234,240); doc.setFont('helvetica','bold'); doc.setFontSize(36);
		doc.text('Certificate of Completion', width/2, 140, { align: 'center' });
		doc.setFont('helvetica','normal'); doc.setFontSize(14); doc.setTextColor(167,176,190);
		doc.text('This certificate is proudly presented to', width/2, 180, { align: 'center' });
		doc.setFont('helvetica','bold'); doc.setFontSize(30); doc.setTextColor(255,255,255);
		doc.text(name, width/2, 230, { align: 'center' });
		doc.setFont('helvetica','normal'); doc.setFontSize(14); doc.setTextColor(167,176,190);
		doc.text('for successfully completing', width/2, 270, { align: 'center' });
		doc.setFont('helvetica','bold'); doc.setFontSize(18); doc.setTextColor(230,234,240);
		doc.text(course, width/2, 300, { align: 'center' });
		const date = new Date().toLocaleDateString();
		doc.setFont('helvetica','normal'); doc.setFontSize(12); doc.setTextColor(167,176,190);
		doc.text(`Date: ${date}`, 80, height-100);
		doc.line(width-260, height-120, width-80, height-120);
		doc.setFont('helvetica','italic'); doc.setFontSize(16); doc.setTextColor(230,234,240);
		doc.text('Md.Kaleembasha', width-170, height-130, { align: 'center' });
		doc.setFont('helvetica','normal'); doc.setFontSize(12); doc.setTextColor(167,176,190);
		doc.text('Authorized Signature', width-170, height-100, { align: 'center' });
		doc.save(`Certificate-${name.replace(/\s+/g,'_')}.pdf`);
	}
})(); 